# Generated by Django 4.1.3 on 2022-12-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=128, null=True)),
                ('opinion_text', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
