# Generated by Django 4.1.3 on 2022-12-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='opinion_text',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='user_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
