# Generated by Django 4.1.3 on 2022-12-29 09:37

from django.db import migrations

from server.apps.user.enums import UserGroup

groups = (
    UserGroup.CUSTOMER.value,
    UserGroup.MANAGER.value,
)

def apply_migration(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Group = apps.get_model('auth', 'Group')
    Group.objects.using(db_alias).bulk_create(
        [Group(name=group_name) for group_name in groups],
    )


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=groups
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration),
    ]
