# Generated by Django 4.1.3 on 2022-12-29 09:25

from django.db import migrations, models
import server.apps.common.validators
import server.apps.offer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to=server.apps.offer.models.file_storage_path)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('short_description', models.CharField(blank=True, max_length=256, null=True)),
                ('full_description', models.CharField(blank=True, max_length=512, null=True)),
                ('amount', models.CharField(blank=True, max_length=16, null=True, validators=[server.apps.common.validators.OnlyDigitsValidator])),
            ],
        ),
    ]
