# Generated by Django 4.1.3 on 2023-01-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='short_description',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
