# Generated by Django 4.1.3 on 2022-12-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentblock', '0003_rename_blog_aboutcontentblock_post_and_more'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Post',
        ),
    ]
