# Generated by Django 4.1.3 on 2022-12-30 11:17

from django.db import migrations, models
import django.db.models.deletion
import server.apps.order.models
import server.apps.order.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        ('user', '0003_alter_bonususer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_with_quantity', models.JSONField(blank=True, default=server.apps.order.models.default_products_with_quantity, help_text='id is your product id and quantity is how much of this product you want to buy', null=True, validators=[server.apps.order.validators.ProductsJsonValidator])),
                ('sum', models.CharField(blank=True, help_text='Sum will appear after saving this object', max_length=32, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=512, null=True)),
                ('products', models.ManyToManyField(to='offer.offer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.bonususer')),
            ],
        ),
    ]
