# Generated by Django 4.1.3 on 2023-01-02 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
        ('order', '0002_order_are_service_terms_accepted_order_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWithQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='offer.offer')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='order.productwithquantity'),
        ),
    ]
