# Generated by Django 4.1.3 on 2023-01-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_productwithquantity_alter_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', '------'), ('Przelew tradycyjny', 'Przelew tradycyjny')], max_length=128, null=True),
        ),
    ]
