# Generated by Django 4.1.3 on 2022-12-29 09:25

from django.db import migrations, models
import django.db.models.deletion
import server.apps.contentblock.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to=server.apps.contentblock.models.file_storage_path)),
                ('content', models.CharField(blank=True, max_length=256, null=True)),
                ('button_text', models.IntegerField(choices=[(None, '(unknown)'), (0, 'Check offer'), (1, 'Find out more')], default='(unknown)')),
                ('button_link', models.CharField(blank=True, default='http://localhost:8002/api/offer', max_length=128, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='AboutContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to=server.apps.contentblock.models.file_storage_path)),
                ('content', models.CharField(blank=True, max_length=256, null=True)),
                ('button_text', models.IntegerField(choices=[(None, '(unknown)'), (0, 'Check offer'), (1, 'Find out more')], default='(unknown)')),
                ('button_link', models.CharField(blank=True, default='http://localhost:8002/api/offer', max_length=128, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.post')),
            ],
        ),
    ]
