# Generated by Django 4.1.3 on 2022-12-29 14:53

from django.db import migrations, models
import django.db.models.deletion
import server.apps.contentblock.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('contentblock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalAboutContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FirstSectionAboutContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to=server.apps.contentblock.models.file_storage_path)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('content_1', models.CharField(blank=True, max_length=512, null=True)),
                ('content_2', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondSectionAboutContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to=server.apps.contentblock.models.file_storage_path)),
                ('content', models.CharField(blank=True, max_length=256, null=True)),
                ('button_text', models.CharField(blank=True, choices=[('', '-------'), ('Check offer', 'Sprawdź ofertę'), ('Find out more', 'Dowiedz się więcej')], default=('', '-------'), max_length=128, null=True)),
                ('button_link', models.SlugField(blank=True, default='', editable=False, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.post')),
            ],
        ),
        migrations.AlterField(
            model_name='homecontentblock',
            name='button_text',
            field=models.CharField(blank=True, choices=[('', '-------'), ('Check offer', 'Sprawdź ofertę'), ('Find out more', 'Dowiedz się więcej')], default=('', '-------'), max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='AboutContentBlock',
        ),
        migrations.AddField(
            model_name='finalaboutcontentblock',
            name='first_section',
            field=models.ManyToManyField(to='contentblock.firstsectionaboutcontentblock'),
        ),
        migrations.AddField(
            model_name='finalaboutcontentblock',
            name='second_section',
            field=models.ManyToManyField(to='contentblock.secondsectionaboutcontentblock'),
        ),
    ]
