# Generated by Django 4.1.3 on 2022-12-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentblock', '0002_finalaboutcontentblock_firstsectionaboutcontentblock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontentblock',
            name='button_link',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homecontentblock',
            name='button_text',
            field=models.CharField(blank=True, choices=[('', '-------'), ('Check offer', 'Sprawdź ofertę'), ('Find out more', 'Dowiedz się więcej')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectionaboutcontentblock',
            name='button_link',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectionaboutcontentblock',
            name='button_text',
            field=models.CharField(blank=True, choices=[('', '-------'), ('Check offer', 'Sprawdź ofertę'), ('Find out more', 'Dowiedz się więcej')], max_length=128, null=True),
        ),
    ]
