# Generated by Django 4.1.3 on 2022-12-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentblock', '0002_aboutcontentblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutcontentblock',
            old_name='blog',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='homecontentblock',
            old_name='blog',
            new_name='post',
        ),
    ]
