# Generated by Django 4.1.3 on 2022-12-30 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentblock', '0003_alter_homecontentblock_button_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalaboutcontentblock',
            name='first_section',
        ),
        migrations.AlterField(
            model_name='homecontentblock',
            name='button_text',
            field=models.CharField(blank=True, choices=[('', '-------'), ('Sprawdź ofertę', 'Sprawdź ofertę'), ('Dowiedz się więcej', 'Dowiedz się więcej')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectionaboutcontentblock',
            name='button_text',
            field=models.CharField(blank=True, choices=[('', '-------'), ('Sprawdź ofertę', 'Sprawdź ofertę'), ('Dowiedz się więcej', 'Dowiedz się więcej')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='finalaboutcontentblock',
            name='first_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contentblock.firstsectionaboutcontentblock'),
        ),
    ]
