# Generated by Django 4.1.3 on 2022-12-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentblock', '0003_rename_blog_aboutcontentblock_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontentblock',
            name='button_text',
            field=models.CharField(choices=[(None, '---------'), ('Sprawdź ofertę', 'Sprawdź ofertę'), ('Dowiedz się więcej', 'Dowiedz się więcej')], default=(None, '---------'), max_length=32),
        ),
        migrations.AlterField(
            model_name='homecontentblock',
            name='button_text',
            field=models.CharField(choices=[(None, '---------'), ('Sprawdź ofertę', 'Sprawdź ofertę'), ('Dowiedz się więcej', 'Dowiedz się więcej')], default=(None, '---------'), max_length=32),
        ),
    ]
