# Generated by Django 4.1.3 on 2023-01-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentblock', '0004_remove_finalaboutcontentblock_first_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstsectionaboutcontentblock',
            name='content_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='firstsectionaboutcontentblock',
            name='content_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homecontentblock',
            name='content',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='secondsectionaboutcontentblock',
            name='content',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
