# Generated by Django 4.1.3 on 2022-12-19 20:46

from django.db import migrations, models
import server.apps.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_and_last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True, validators=[server.apps.common.validators.OnlyDigitsValidator])),
                ('message', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
